# Generated by Django 2.2.9 on 2023-02-07 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siebel', '0061_auto_20220701_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='siebelconfiguration',
            name='queue_piano',
            field=models.BooleanField(default=False, verbose_name='Bloqueo por cola de envio'),
        ),
    ]
