# Generated by Django 2.2.9 on 2023-02-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siebel', '0062_siebelconfiguration_queue_piano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siebelconfiguration',
            name='queue_piano',
        ),
        migrations.AddField(
            model_name='siebelconfiguration',
            name='queue_piano_conciliation',
            field=models.BooleanField(default=False, verbose_name='Bloqueo por cola de envio de conciliaciones'),
        ),
        migrations.AddField(
            model_name='siebelconfiguration',
            name='queue_piano_delivery',
            field=models.BooleanField(default=False, verbose_name='Bloqueo por cola de envio de deliverys'),
        ),
        migrations.AddField(
            model_name='siebelconfiguration',
            name='queue_piano_vouchers',
            field=models.BooleanField(default=False, verbose_name='Bloqueo por cola de envio de renovaciones'),
        ),
    ]
