# Generated by Django 2.2.9 on 2022-12-26 21:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, verbose_name='ARC data')),
                ('arc_state', models.NullBooleanField()),
                ('created_on', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Fecha de registro')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': '[ARC] Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.BigIntegerField(blank=True, null=True, verbose_name='Code')),
                ('event_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo')),
                ('message', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Message')),
                ('site', models.CharField(blank=True, max_length=20, null=True, verbose_name='Site')),
                ('timestamp', models.BigIntegerField(blank=True, null=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': '[ARC] Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(null=True, verbose_name='Fecha de inicio')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('report_type', models.CharField(choices=[('financial-report', 'Transacciones'), ('subscription-event', 'Eventos'), ('refund-audit', 'Reembolsos'), ('future-failed-payment', 'Próximos pagos'), ('subscription-summary', 'Resumen de suscripciones')], default='financial-report', max_length=50, null=True, verbose_name='Tipo')),
                ('site', models.CharField(choices=[('elcomercio', 'El Comercio'), ('gestion', 'Gestión')], max_length=20, null=True, verbose_name='Portal')),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Request')),
                ('result', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Responce')),
                ('error', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Error')),
                ('data', models.FileField(blank=True, null=True, upload_to='', verbose_name='Reporte')),
                ('records', models.IntegerField(blank=True, null=True, verbose_name='Número de registros')),
                ('hits', models.IntegerField(blank=True, default=0, null=True, verbose_name='Número de intentos')),
                ('data_loaded', models.NullBooleanField(verbose_name='Datos cargados')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': '[ARC] Reportes',
            },
        ),
    ]
