# Generated by Django 2.2.9 on 2022-12-26 21:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paywall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('subscription_id_piano', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID Piano')),
                ('type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LoadReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('export_id_recognition', models.CharField(blank=True, max_length=128, null=True, verbose_name='Export Id Recognition')),
                ('export_id_transaction_report', models.CharField(blank=True, max_length=128, null=True, verbose_name='Export Id Transaction')),
                ('brand', models.CharField(blank=True, max_length=20, null=True, verbose_name='Marca')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentPiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('siebel_hits', models.IntegerField(default=0, verbose_name='Intentos a Siebel')),
                ('siebel_request', models.TextField(blank=True, null=True)),
                ('siebel_response', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=False, verbose_name='state')),
                ('cod_response', models.NullBooleanField(verbose_name='Cod response')),
            ],
            options={
                'verbose_name': 'Pago Siebel',
                'verbose_name_plural': 'Pagos Siebel',
            },
        ),
        migrations.CreateModel(
            name='RenovationPiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('siebel_hits', models.IntegerField(default=0, verbose_name='Intentos a Siebel')),
                ('siebel_request', models.TextField(blank=True, null=True)),
                ('siebel_response', models.TextField(blank=True, null=True)),
                ('state', models.NullBooleanField(verbose_name='Cod response')),
            ],
            options={
                'verbose_name': 'Renovacion Siebel',
                'verbose_name_plural': 'Renovaciones Siebel',
            },
        ),
        migrations.CreateModel(
            name='ReportTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('transaction_id', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleOrderPiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('siebel_hits', models.IntegerField(default=0, verbose_name='Intentos a Siebel')),
                ('siebel_request', models.TextField(blank=True, null=True)),
                ('siebel_response', models.TextField(blank=True, null=True)),
                ('delivery', models.IntegerField(blank=True, null=True, verbose_name='Delivery')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Ordenes de Venta Siebel',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('delivery', models.IntegerField(blank=True, null=True, verbose_name='Delivery')),
                ('subscription_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID')),
                ('app_id', models.CharField(max_length=64, null=True, verbose_name='APP ID')),
                ('uid', models.CharField(blank=True, max_length=128, null=True, verbose_name='User ID (UID)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio de Suscripción')),
                ('note', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nota')),
                ('locked', models.NullBooleanField(verbose_name='Bloqueado')),
                ('sent_club', models.BooleanField(blank=True, default=False, null=True, verbose_name='sent_club')),
                ('payment_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paywall.PaymentProfile', verbose_name='Perfil de pago')),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionMatchArcPiano',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('subscription_id_piano', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID Piano')),
                ('subscription_id_arc', models.BigIntegerField(default=0, verbose_name='ID de ARC')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionToFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('subscription_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID')),
                ('payu_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payu TransactionId')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('plan_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('plan_description', models.CharField(blank=True, max_length=168, null=True, verbose_name='Descripcion')),
                ('term_id', models.CharField(max_length=64, null=True, verbose_name='Term Id')),
                ('app_id', models.CharField(max_length=64, null=True, verbose_name='APP ID')),
                ('period', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Mensual'), (2, 'Trimestral'), (3, 'Semestral'), (4, 'Anual')], default=0, null=True, verbose_name='Period')),
                ('net_price_first_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Price Primer pago')),
                ('indefinite_promotion', models.NullBooleanField(verbose_name='Promocion Indefinida')),
                ('siebel_code_promo', models.CharField(blank=True, max_length=105, null=True, verbose_name='Codigo promocional')),
                ('ticket_reference', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ticket de referencia')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Term Data')),
                ('migrated', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Si'), (2, 'No')], default=0, null=True, verbose_name='Migrado')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_product', to='paywall.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': '[Config] Planes',
                'unique_together': {('term_id', 'app_id')},
            },
        ),
        migrations.CreateModel(
            name='TransactionsWithNewDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('subscription_id_piano', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID Piano')),
                ('external_tx_id', models.CharField(blank=True, max_length=80, null=True, verbose_name='External Tx ID')),
                ('access_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accesss From')),
                ('access_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Access To')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='Brand')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('siebel_hits', models.IntegerField(default=0, verbose_name='Intentos a Siebel')),
                ('siebel_request', models.TextField(blank=True, null=True)),
                ('siebel_response', models.TextField(blank=True, null=True)),
                ('sent_to_siebel', models.NullBooleanField(verbose_name='Enviado a Siebel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('external_tx_id', models.CharField(blank=True, max_length=80, null=True, verbose_name='External Tx ID')),
                ('tx_type', models.CharField(blank=True, max_length=70, null=True, verbose_name='Tx Type')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='Status')),
                ('term_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Term name')),
                ('term_identifier', models.CharField(blank=True, max_length=128, null=True, verbose_name='Term ID')),
                ('subscription_id_str', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID')),
                ('user_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='User ID (UID)')),
                ('initial_transaction', models.NullBooleanField(verbose_name='Transaccion inicial')),
                ('initial_payment', models.NullBooleanField(verbose_name='Payment inicial')),
                ('access_from', models.CharField(blank=True, max_length=100, null=True, verbose_name='Accesss From')),
                ('access_to', models.CharField(blank=True, max_length=100, null=True, verbose_name='Access To')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Payment date')),
                ('access_from_date', models.DateTimeField(blank=True, null=True, verbose_name='Access From Date')),
                ('amount', models.IntegerField(null=True, verbose_name='Amount')),
                ('payu_order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payu OrderId')),
                ('payu_transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payu TransactionId')),
                ('payment_source_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Payment Source Type')),
                ('reconciliation_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reconciliation Id')),
                ('id_transaction_paymentos', models.CharField(blank=True, max_length=100, null=True, verbose_name='Id Transaction PaymentOS')),
                ('block_sending', models.NullBooleanField(verbose_name='Bloquear envio')),
                ('observation', models.CharField(blank=True, max_length=150, null=True, verbose_name='Observacion')),
                ('devolution', models.NullBooleanField(verbose_name='Devolución')),
                ('report_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('payment_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_payment_profile', to='paywall.PaymentProfile', verbose_name='Perfil de pago')),
                ('siebel_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siebel_payment_transaction', to='piano.PaymentPiano', verbose_name='Siebel Payment')),
                ('siebel_renovation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='siebel_renovation_transaction', to='piano.RenovationPiano', verbose_name='Siebel Renovation')),
                ('siebel_sale_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_siebel_sale_order', to='piano.SaleOrderPiano', verbose_name='Siebel O.V')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_transaction', to='piano.Subscription', verbose_name='Subscripcion')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_term', to='piano.Term', verbose_name='Term')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_term', to='piano.Term', verbose_name='Term'),
        ),
        migrations.CreateModel(
            name='LowSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('subs_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID')),
                ('user_email', models.CharField(blank=True, max_length=160, null=True, verbose_name='User email')),
                ('resource_name', models.CharField(blank=True, max_length=160, null=True, verbose_name='Resource Name')),
                ('resource_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Resource ID (RID)')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Inicio de Suscripción')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('low_subscription', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de baja de Suscripción')),
                ('user_access_expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='User Access Expiration Date')),
                ('exclude_to_send_siebel', models.NullBooleanField(verbose_name='Excluido de envio a Siebel')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_low', to='piano.Subscription', verbose_name='Subscripcion')),
                ('unsubscribe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='low_subscriptions_unsubscribe', to='piano.Unsubscribe', verbose_name='Unsubscribe')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('app_id', 'subscription_id')},
        ),
    ]
