# Generated by Django 2.2.9 on 2023-01-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0044_subscriptiontofix'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnableSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('subscription_id_piano', models.CharField(blank=True, max_length=128, null=True, verbose_name='Subscription ID Piano')),
                ('type', models.CharField(blank=True, max_length=128, null=True, verbose_name='Tipo')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
