# Generated by Django 2.2.9 on 2023-01-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0045_enablesubscriptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('siebel_code_promo', models.CharField(blank=True, max_length=128, null=True, verbose_name='Name')),
                ('net_price_first_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Price Primer pago')),
                ('ticket_reference', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ticket de referencia')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_term', to='piano.Term')),
            ],
            options={
                'ordering': ('-created',),
                'abstract': False,
            },
        ),
    ]
