# Generated by Django 2.2.9 on 2023-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0047_promotionpiano'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotionterm',
            name='promotion_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='promotion piano id'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_price',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='original_price'),
        ),
    ]
