# Generated by Django 2.2.9 on 2023-01-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0048_auto_20230125_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionterm',
            name='siebel_code_promo',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='siebel_code_promo'),
        ),
    ]
