# Generated by Django 2.2.9 on 2023-01-31 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piano', '0050_promotionterm_indefinite_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='renovationpiano',
            name='payu_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Payu TransactionId'),
        ),
    ]
