# Generated by Django 2.2.9 on 2022-12-26 21:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arcsubs', '0001_initial'),
        ('paywall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('state', models.CharField(blank=True, choices=[('1', 'Pendiente de Pago'), ('2', 'Cancelado'), ('3', 'Expirado'), ('4', 'Anulado')], max_length=2, null=True, verbose_name='Estado')),
                ('observation', models.CharField(blank=True, max_length=120, null=True, verbose_name='Observación')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='Currency')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Amount')),
                ('date_expiry', models.DateTimeField(blank=True, null=True, verbose_name='dateExpiry')),
                ('payment_concept', models.CharField(blank=True, max_length=120, null=True, verbose_name='paymentConcept')),
                ('additional_data', models.CharField(blank=True, max_length=120, null=True, verbose_name='additionalData')),
                ('user_email', models.CharField(max_length=128, null=True, verbose_name='userEmail')),
                ('user_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='UUID')),
                ('user_name', models.CharField(max_length=128, null=True, verbose_name='userName')),
                ('lastname_father', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellido Paterno')),
                ('lastname_mother', models.CharField(blank=True, max_length=128, null=True, verbose_name='Apellido Materno')),
                ('user_ubigeo', models.CharField(blank=True, max_length=80, null=True, verbose_name='userUbigeo')),
                ('user_country', models.CharField(blank=True, max_length=120, null=True, verbose_name='userCountry')),
                ('user_document_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CEX', 'Carné extranjeria'), ('CDI', 'Carné de diplomático'), ('PAS', 'Pasaporte'), ('OTRO', 'OTRO')], max_length=10, null=True, verbose_name='userDocumentType')),
                ('user_document_number', models.CharField(max_length=80, null=True, verbose_name='userDocumentNumber')),
                ('user_code_country', models.CharField(max_length=16, null=True, verbose_name='userCodeCountry')),
                ('user_phone', models.CharField(blank=True, max_length=16, null=True, verbose_name='userPhone')),
                ('service_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='serviceId')),
                ('price_code', models.CharField(blank=True, max_length=16, null=True, verbose_name='PRICE CODE')),
                ('cip', models.CharField(blank=True, max_length=50, null=True, verbose_name='CIP')),
                ('token_authorization', models.CharField(blank=True, max_length=350, null=True, verbose_name='Token Authorization')),
                ('request_body', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Cuerpo de Envio')),
                ('response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Respuesta')),
                ('cip_url', models.CharField(blank=True, max_length=120, null=True, verbose_name='cipUrl')),
                ('transaction_code_response', models.CharField(blank=True, max_length=50, null=True, verbose_name='transactionCodeResponse')),
                ('response_state', models.SmallIntegerField(blank=True, null=True, verbose_name='Codigo de Respuesta PE')),
                ('response_date_expiry', models.DateTimeField(blank=True, null=True, verbose_name='dateExpiryResponse')),
                ('message', models.CharField(blank=True, max_length=90, null=True, verbose_name='Mensaje')),
                ('linked', models.CharField(blank=True, choices=[('1', 'Linkeado'), ('2', 'Error en el Linkeo'), ('3', 'No enviado')], max_length=2, null=True, verbose_name='Estado Linked')),
                ('linked_request', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Peticion Linked')),
                ('linked_response', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Respuesta Linked')),
                ('subscription_arc_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='Subscription ARC ID')),
                ('arc_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_cip', to='arcsubs.ArcUser', verbose_name='Cliente')),
                ('payment_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cip_payment_profile', to='paywall.PaymentProfile', verbose_name='Perfil de pago')),
            ],
            options={
                'verbose_name': 'CIP User',
                'verbose_name_plural': 'CIPs Users',
            },
        ),
        migrations.CreateModel(
            name='PaymentPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('siebel_hits', models.IntegerField(default=0, verbose_name='Intentos a Siebel')),
                ('siebel_request', models.TextField(blank=True, null=True)),
                ('siebel_response', models.TextField(blank=True, null=True)),
                ('state', models.BooleanField(default=False, verbose_name='state')),
                ('cod_response', models.IntegerField(blank=True, null=True, verbose_name='cod_response')),
                ('rate_total_sent_conciliation', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Pago Siebel',
                'verbose_name_plural': 'Pagos Siebel',
            },
        ),
        migrations.CreateModel(
            name='PaymentTrackingPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('url_referer', models.CharField(blank=True, max_length=350, null=True, verbose_name='Url Referer')),
                ('medium', models.CharField(blank=True, max_length=80, null=True, verbose_name='Medio')),
                ('device', models.CharField(blank=True, choices=[('1', 'mobile'), ('2', 'desktop'), ('3', 'tablet'), ('4', 'otros')], max_length=40, null=True, verbose_name='Dispositivo')),
                ('confirm_subscription', models.IntegerField(blank=True, choices=[(1, 'Acepta doble compra'), (2, 'No acepta doble compra'), (3, 'No paso por el flujo')], null=True, verbose_name='Confirmacion de suscripcion')),
                ('user_agent', models.CharField(blank=True, max_length=350, null=True, verbose_name='User Agent')),
                ('user_agent_str', models.CharField(blank=True, max_length=350, null=True, verbose_name='Browser')),
                ('browser_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Browser - version')),
                ('os_version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sistema Operativo')),
                ('device_user_agent', models.CharField(blank=True, max_length=100, null=True, verbose_name='family - brand - model')),
                ('is_pwa', models.IntegerField(blank=True, choices=[(1, 'SI'), (2, 'NO')], null=True, verbose_name='PWA')),
            ],
            options={
                'verbose_name': 'Seguimiento de Suscripción PE',
                'verbose_name_plural': 'Seguimiento de Suscripciones PE',
            },
        ),
        migrations.CreateModel(
            name='SaleOrderPE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('siebel_hits', models.IntegerField(default=0, verbose_name='Intentos a Siebel')),
                ('siebel_request', models.TextField(blank=True, null=True)),
                ('siebel_response', models.TextField(blank=True, null=True)),
                ('delivery', models.IntegerField(blank=True, null=True, verbose_name='Delivery')),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Ordenes de Venta Siebel',
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado')),
                ('last_updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Modificado')),
                ('event_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='eventType')),
                ('sub_type', models.CharField(blank=True, choices=[('1', 'Regular'), ('2', 'Pruebas')], max_length=2, null=True, verbose_name='SubTipo')),
                ('operation_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='operationNumber')),
                ('cip', models.CharField(blank=True, max_length=50, null=True, verbose_name='CIP')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='currency')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=15, null=True, verbose_name='amount')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('transaction_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='transactionCode')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Payment data')),
                ('arc_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_payment', to='arcsubs.ArcUser', verbose_name='Cliente')),
                ('cip_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_notification_cip', to='pagoefectivo.CIP', verbose_name='CIP OBJ')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.AddField(
            model_name='cip',
            name='payment_tracking_pe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_tracking_cip', to='pagoefectivo.PaymentTrackingPE', verbose_name='PaymentTrackingPE'),
        ),
        migrations.AddField(
            model_name='cip',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_cip', to='paywall.Plan', verbose_name='Plan'),
        ),
        migrations.AddField(
            model_name='cip',
            name='siebel_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siebel_payment_pe', to='pagoefectivo.PaymentPE', verbose_name='Siebel Payment'),
        ),
        migrations.AddField(
            model_name='cip',
            name='siebel_sale_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='siebel_sale_order_pe', to='pagoefectivo.SaleOrderPE', verbose_name='Siebel'),
        ),
        migrations.AddField(
            model_name='cip',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='paywall.Subscription', verbose_name='Subscripción'),
        ),
    ]
