# Generated by Django 2.2.9 on 2022-12-26 21:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ubigeo_depc', models.CharField(blank=True, max_length=8, null=True, verbose_name='cod. departamento')),
                ('ubigeo_depn', models.CharField(blank=True, max_length=64, null=True, verbose_name='nombre departamento')),
                ('ubigeo_provc', models.CharField(blank=True, max_length=8, null=True, verbose_name='cod. provincia')),
                ('ubigeo_provn', models.CharField(blank=True, max_length=64, null=True, verbose_name='nombre provincia')),
                ('ubigeo_disc', models.CharField(blank=True, max_length=8, null=True, verbose_name='cod. distrito')),
                ('ubigeo_disn', models.CharField(blank=True, max_length=64, null=True, verbose_name='nombre distrito')),
                ('siebel_codigo', models.IntegerField(blank=True, null=True, verbose_name='siebel codigo')),
                ('siebel_prefijo', models.CharField(blank=True, max_length=32, null=True, verbose_name='siebel prefijo')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha registro')),
                ('coordenadas', django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='["lat","lng"]', null=True, verbose_name='coordenadas por default')),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (0, 'Inactivo')], default=0, null=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'Ubigeo',
                'verbose_name_plural': 'Ubigeo',
            },
        ),
    ]
